version: '3.5'
services:

  endlessh:
    container_name: endlessh
    image: shizunge/endlessh-go:latest
    restart: unless-stopped
    #user: root
    command:
      - "-logtostderr"
      - "-v=1"
      - -enable_abuseipdb
      - -abuse_ipdb_api_key ""
    networks:
      - example_network
    ports:
      - 2222:2222 # SSH port
      - 127.0.0.1:2112:2112 # Prometheus metrics port
    volumes:
    environment:

networks:
  example_network:
